/* ===========================================================
   The First Academy — Student Gateway · ACTIVITY LIBRARY
   -----------------------------------------------------------
   Every card on the site comes from this file. To add one,
   copy a line and edit it.

   Fields
     id    unique short name (letters / dashes)
     n     activity name              p   provider
     u     link                       e   emoji (used when no image)
     img   optional cover image (path after IMG, or full https URL)
     g     [lowest grade, highest grade]   (4 … 12)
     i     interests: ai code math sci art lang safe build career
     t     type: game | create | puzzle | course
     time  quick (≤20 min) | hour (~1 hour) | long (several sessions)
     cert  true if it gives a certificate / badge on completion
     need  optional: "webcam" | "account" | "download"
     hoai  true if it is part of CSforAll / Code.org "Hour of AI"
     en/ar one-line description in English / Arabic
   =========================================================== */

const IMG = "https://contentful-images.code.org/27jkibac934d/";

const ACTIVITIES = [

/* ---------------- Hour of AI (CSforAll) — student-playable picks ---------------- */
{ id:"mix-move", n:"Mix & Move with AI", p:"Code.org", u:"https://studio.code.org/s/mix-move-ai-2025/reset", img:"5VAjHP5PYyuJ0Vmgrk2nni/de51781ca76af581a537887b50e95067/Mix_MoveCard.png", e:"💃", g:[4,12], i:["ai","art","code"], t:"create", time:"hour", cert:true, hoai:true,
  en:"Design a dancer, code a music remix and choreograph a dance using AI prompts.",
  ar:"صمّم راقصاً، وبرمج ريمكس موسيقي، وصمّم رقصة باستخدام أوامر الذكاء الاصطناعي." },
{ id:"dance-ai", n:"Dance Party: AI Edition", p:"Code.org", u:"https://studio.code.org/courses/dance-ai-2023/units/1/lessons/1/levels/1", img:"5R6KQ5tDtBCwrphi7ycSbJ/8a345d125a74cc7a88a5eaaa3a62ace7/dance-party-activity-ai-edition-cropped.avif", e:"🎶", g:[4,8], i:["ai","art","code"], t:"game", time:"hour", cert:true, hoai:true,
  en:"Code a virtual dance party with today's top songs while learning how AI helps.",
  ar:"برمج حفلة رقص افتراضية مع أشهر الأغاني وتعلّم كيف يساعد الذكاء الاصطناعي." },
{ id:"ai-oceans", n:"AI for Oceans", p:"Code.org", u:"https://studio.code.org/s/oceans/reset", img:"3HGqIPlNknJPhDp1ky4PKI/d4781f3c0554f87891e1b437dc0592dc/oceans.jpg", e:"🐠", g:[4,12], i:["ai","sci"], t:"game", time:"hour", cert:true, hoai:true,
  en:"Train an AI to clean the ocean — and discover training data and bias.",
  ar:"درّب ذكاءً اصطناعياً لتنظيف المحيط — واكتشف بيانات التدريب والتحيّز." },
{ id:"music-jam", n:"Music Lab: Jam Session", p:"Code.org", u:"https://studio.code.org/s/music-jam-2024/reset", img:"4gJcj1Ns6tctlsNgViToqP/5a222ae860d70044d4e03629bc8b47ed/music_lab_jam.jpg", e:"🎧", g:[4,12], i:["art","code","ai"], t:"create", time:"hour", cert:true, hoai:true,
  en:"Remix real tracks with code — sequencing, loops and AI-made beats.",
  ar:"أعد مزج مقاطع موسيقية حقيقية بالبرمجة — تسلسل وتكرار وإيقاعات بالذكاء الاصطناعي." },
{ id:"web-lab", n:"Intro to Web Lab", p:"Code.org", u:"https://studio.code.org/courses/intro-to-web-lab/units/1", img:"3GnWI11XDwEXInn8pWCPQL/fa2b83456b206d7c321d5b2043549f29/weblab-intro-cover.jpg", e:"🌐", g:[8,12], i:["code","ai"], t:"course", time:"hour", cert:true, hoai:true,
  en:"Build a web page in an AI-powered editor and learn to use AI thoughtfully.",
  ar:"ابنِ صفحة ويب في محرّر مدعوم بالذكاء الاصطناعي وتعلّم استخدامه بحكمة." },
{ id:"mc-first-night", n:"Minecraft: The First Night", p:"Minecraft Education", u:"https://aka.ms/thefirstnightlesson", img:"5bSnSdULjNL9PFuzDy5rHK/151ae934531376ce80aae5a1444988cd/V9_MCEDU_HOAI_TheFirstNight_3840x2160_PROVISIONAL_FINAL__1_.jpeg", e:"⛏️", g:[4,12], i:["ai","code"], t:"game", time:"hour", need:"account", hoai:true,
  en:"Guide an AI helper to survive your first night — and learn why AI needs humans.",
  ar:"وجّه مساعداً ذكياً لتنجو في ليلتك الأولى — واكتشف لماذا يحتاج الذكاء الاصطناعي إلى الإنسان." },
{ id:"mc-reed-smart", n:"Reed Smart: AI Detective", p:"Minecraft Education", u:"https://aka.ms/reedsmart", img:"7widOAHGu6yFpRbo7svCXY/f65245fbdca850241c40c3b6aeabf0d7/MCEDU_Reed_Smart_AI_Detective_Minecraft_Education_Web_Lesson_Page_480x270__1_.png", e:"🕵️", g:[4,12], i:["ai","safe"], t:"game", time:"hour", need:"account", hoai:true,
  en:"Solve mysteries of AI misuse — spot deepfakes and AI-generated content.",
  ar:"حلّ ألغاز إساءة استخدام الذكاء الاصطناعي — واكتشف المقاطع المزيّفة والمحتوى المولّد." },
{ id:"mc-generation-ai", n:"Minecraft: Generation AI", p:"Minecraft Education", u:"https://aka.ms/HourofCode2023", img:"5SuBAE9JXePWZAWGpLIfJ4/d39591e8115641e313c67ccb3993690d/generation_ai.jpg", e:"🧱", g:[4,12], i:["ai","code"], t:"game", time:"hour", need:"account", hoai:true,
  en:"Code in blocks or Python to build a better, more responsible AI.",
  ar:"برمج بالكتل أو بايثون لتبني ذكاءً اصطناعياً أفضل وأكثر مسؤولية." },
{ id:"mc-fairgrounds", n:"Fantastic Fairgrounds", p:"Minecraft Education", u:"https://aka.ms/FantasticFairgrounds", img:"5NpCjEvEt6WDF3LdJByLYH/2e88d928b034fe92859116d4b0a6fadd/MCEDU_FantasticFairgrounds_PDP_800x450.png", e:"🎡", g:[4,12], i:["ai","art","math"], t:"game", time:"hour", need:"account", hoai:true,
  en:"Team up with an AI assistant to solve bee, light-show and art challenges.",
  ar:"تعاون مع مساعد ذكي لحل تحديات النحل وعروض الإضاءة والفن." },
{ id:"mc-cybersafe", n:"CyberSafe AI: Dig Deeper", p:"Minecraft Education", u:"https://education.minecraft.net/en-us/lessons/cybersafe-ai-dig-deeper", img:"1J5nz5gM4y1e7sob7yuzvZ/b7c47c636151a075d47266d81601ae2d/MCEDU_CyberSafeAIDigDeeper_LessonPage_480x270.png", e:"🔐", g:[4,12], i:["safe","ai"], t:"game", time:"hour", need:"account", hoai:true,
  en:"AI makes mistakes! Fact-check it, protect privacy and design 3D animals.",
  ar:"الذكاء الاصطناعي يخطئ! تحقّق من معلوماته واحمِ الخصوصية وصمّم حيوانات ثلاثية الأبعاد." },
{ id:"mc-ai-for-good", n:"Minecraft: AI for Good", p:"Minecraft Education", u:"https://aka.ms/minecraft-aiforgood", img:"2WRl57x6rf3Zq8cyeSxD03/c7a4562f472fdfffdc196319ae545796/MCEDU_HOC_LessonPDP.png", e:"🔥", g:[4,9], i:["ai","sci","code"], t:"game", time:"hour", need:"account", hoai:true,
  en:"Program the Agent to collect forest-fire data like a real AI system.",
  ar:"برمج الوكيل لجمع بيانات حرائق الغابات كما يفعل نظام ذكاء اصطناعي حقيقي." },
{ id:"ai-quests", n:"AI Quests", p:"Google Research", u:"https://research.google/ai-quests", img:"3sQmMOFTNiHhJxlJITe5CX/00b866cc15c81fa77d18265207f16ffc/AI-Quests.jpg", e:"🧭", g:[5,9], i:["ai","sci"], t:"game", time:"hour", hoai:true,
  en:"Step into the shoes of Google researchers using AI on real-world problems.",
  ar:"كن باحثاً في جوجل واستخدم الذكاء الاصطناعي لحل مشكلات حقيقية." },
{ id:"scratch-face", n:"Scratch Face Sensing", p:"Scratch Foundation", u:"https://scratch.mit.edu/projects/1208621527/editor?tutorial=face-sensing", img:"77CtcMzgESrGaS9CE3YWa2/d93936f77020262505c1d5d6a8dfd8ca/ScratchFaceSensing_HourofAI-notext_480w.png", e:"🙂", g:[4,10], i:["ai","code","art"], t:"create", time:"hour", need:"webcam", hoai:true,
  en:"Control a game by tilting your face, draw with your nose, make face filters.",
  ar:"تحكّم بلعبة بإمالة وجهك، وارسم بأنفك، واصنع فلاتر للوجه." },
{ id:"bug-arena", n:"MakeCode Bug Arena", p:"Microsoft MakeCode", u:"https://aka.ms/bug-arena", img:"3ra3aqhXkIkPgqQsCGVLUZ/0db53abdcb87f21eb20558b76b2b77aa/BugArena_480x360.png", e:"🐞", g:[5,12], i:["ai","code"], t:"game", time:"hour", hoai:true,
  en:"Code and train a smart AI bug, then battle other bugs in the arena.",
  ar:"برمج ودرّب حشرة ذكية ثم نافس حشرات أخرى في الساحة." },
{ id:"slither-slam", n:"Slither Slam", p:"Microsoft VS Code for Edu", u:"https://aka.ms/slither-slam", img:"5J9TYXFCg4ij9icZWFRyvG/fe2343d35220687f894c3601f5eef612/slitherslam.png", e:"🐍", g:[8,12], i:["ai","code"], t:"game", time:"hour", hoai:true,
  en:"Use prompt engineering to win a fast-paced Snake tournament.",
  ar:"استخدم هندسة الأوامر للفوز في بطولة لعبة الثعبان السريعة." },
{ id:"fruit-fighter", n:"Fruit Fighter", p:"Tynker", u:"https://www.tynker.com/hour-of-code/fruit-fighter", img:"1phKLOmwxSJOv9bw5Qrw7R/6acca6f5d4d13fe8b3a2050931fdcfae/Tynker_-_Fruit_Fighter_430x240.png", e:"🍉", g:[8,12], i:["code","ai"], t:"create", time:"hour", need:"webcam", hoai:true,
  en:"Recreate a fruit-slicing game in p5.js — controlled by your webcam.",
  ar:"أعد بناء لعبة تقطيع الفواكه بلغة p5.js — وتحكّم بها عبر الكاميرا." },
{ id:"weather-control", n:"Weather Control", p:"Tynker", u:"https://www.tynker.com/hour-of-code/weather-control", img:"2QvnuDqWAQ2vZlVLgTC3up/15f50fde60d345eb5b8f20a4da91246d/Tynker_-_Weather_Control_480x360.png", e:"⛈️", g:[4,7], i:["ai","code","sci"], t:"create", time:"hour", need:"webcam", hoai:true,
  en:"Use AI body-tracking to control the weather with hand gestures.",
  ar:"استخدم تتبّع الجسم بالذكاء الاصطناعي للتحكّم بالطقس بحركات يديك." },
{ id:"tickle-monster", n:"Tickle Monster", p:"Tynker", u:"https://www.tynker.com/hour-of-code/tickle-monster", img:"4aQh6d2lMz1uDql3HhKeMY/fb8d642dff7b7c64d835eed8ae92f5c6/Tynker_-_Tickle_Monster_480x360.png", e:"👾", g:[4,7], i:["ai","art","code"], t:"create", time:"hour", need:"webcam", hoai:true,
  en:"Bring a monster to life that reacts to your hand movements.",
  ar:"أحيِ وحشاً ظريفاً يتفاعل مع حركات يديك." },
{ id:"balancing-act", n:"Balancing Act", p:"Tynker", u:"https://www.tynker.com/hour-of-code/balancing-act", img:"4WmnZ4NsTNUEL3Lg3UcsYl/6ce6248bb29e309399c11929cee9c410/Tynker_-_Balancing_Act_430x240.png", e:"⚖️", g:[4,8], i:["code","sci","ai"], t:"game", time:"hour", need:"webcam", hoai:true,
  en:"Build a physics game where you balance a ball using head movements.",
  ar:"ابنِ لعبة فيزيائية توازن فيها كرة بحركات رأسك." },
{ id:"career-tours", n:"AI Career Tours", p:"Amazon Future Engineer", u:"https://www.amazonfutureengineer.in/en/career-tours/amazon-music-tour/video-full-ai", img:"6sNY7ZR0PgpX6v7tAzEZ97/08cbe219b2db80361df15bc471f65226/AmazonMusicCareers.png", e:"🚀", g:[8,12], i:["career","ai"], t:"course", time:"quick", hoai:true,
  en:"Go inside a music recommender and meet the people who build AI products.",
  ar:"ادخل إلى نظام توصيات موسيقية وتعرّف على من يبنون منتجات الذكاء الاصطناعي." },
{ id:"translation-station", n:"Translation Station", p:"Digital Moment", u:"https://resources.digitalmoment.org/hour-of-ai-2025-wip/", img:"1OEqkQKY1stK2JginbxBkp/9363f5669bf5b0580aef53f6590bd0bf/black_480.png", e:"🗣️", g:[4,8], i:["lang","ai"], t:"game", time:"hour", hoai:true,
  en:"Be a language detective — test AI translation between Arabic, English and more.",
  ar:"كن محقّقاً لغوياً — اختبر الترجمة الآلية بين العربية والإنجليزية وغيرها." },
{ id:"gpt2-magic", n:"The Magic Inside GPT-2", p:"MyAI101", u:"https://myai101.com/hourofai/gpt2", img:"uvwymbNlgCj6O0kaT8G9k/3965955761e912c02072395f85ac0d30/GPT-2_cover_image__1_.png", e:"🧠", g:[9,12], i:["ai","lang"], t:"puzzle", time:"hour", hoai:true,
  en:"An interactive look inside a language model — tokens, attention, prediction.",
  ar:"جولة تفاعلية داخل نموذج لغوي — الرموز والانتباه والتنبؤ." },
{ id:"robogarden", n:"RoboGarden AI Labs", p:"RoboGarden", u:"https://playground.robogarden.ca/hourofAI/steam/all", img:"4mKyPrVwP6jBha9hXmmAlM/b8312a27212ec5c6a894a8527b8a9181/RG_AI_Lab_Cover.png", e:"🛸", g:[4,12], i:["code","ai","sci"], t:"game", time:"hour", hoai:true,
  en:"Code a drone to explore continents, then turn its data into AI creations.",
  ar:"برمج طائرة مسيّرة لاستكشاف القارات ثم حوّل بياناتها إلى إبداعات بالذكاء الاصطناعي." },
{ id:"ml-music", n:"Machine Learning & Music", p:"CodeHS", u:"http://codehs.com/hourofai/music", img:"7uyPtequl2CxLZyzlcQtGD/c1d1312fc83ec42d0de4d085fd5b17f1/Machine_Learning_and_Music_Classification_480x360.png", e:"🎼", g:[8,12], i:["ai","art","sci"], t:"create", time:"hour", hoai:true,
  en:"Train a model to recognise music genres and test how data changes accuracy.",
  ar:"درّب نموذجاً للتعرّف على أنواع الموسيقى واختبر أثر البيانات على الدقة." },
{ id:"llm-math", n:"LLMs: Math, not Magic", p:"Hello World CS", u:"https://helloworldcs.org/hour-of-ai", img:"16TwsqPx0GUXatHnhyCUwY/3b19ae7c3e9531fdb27530fb7f7ae4b1/hwcs-HoAI-480x360.png", e:"🔢", g:[6,10], i:["ai","math"], t:"puzzle", time:"hour", hoai:true,
  en:"See how chatbots write one token at a time using maths, not magic.",
  ar:"اكتشف كيف تكتب روبوتات المحادثة كلمة بكلمة باستخدام الرياضيات لا السحر." },
{ id:"drone-command", n:"Drone Command: Operation Uplink", p:"NSWC Carderock", u:"https://sjwines.github.io/", img:"2HVnrP5s4nSTTaYg8uJkhO/75e73b7b83873c7bac07999f067ffc6e/Drone_Command_Operation_Uplink_Title_Screen.png", e:"🚁", g:[8,12], i:["code","ai"], t:"game", time:"long", hoai:true,
  en:"Build an ocean-rescue game in MakeCode Arcade and code an AI advisor.",
  ar:"ابنِ لعبة إنقاذ بحري في MakeCode Arcade وبرمج مستشاراً ذكياً." },
{ id:"rosebud", n:"Build a Puzzle Game with AI", p:"Rosebud AI", u:"https://lab.rosebud.ai/hour-of-ai", img:"29h9IDZBlaawSdKUCo83h8/6df40ee7436b4d7c67f81ca89a1c488b/Hour_of_AI_Thumbnail.png", e:"🧩", g:[7,12], i:["ai","code","lang"], t:"create", time:"long", hoai:true,
  en:"Describe a world in words and watch it become a playable puzzle game.",
  ar:"صِف عالماً بالكلمات وشاهده يتحوّل إلى لعبة ألغاز قابلة للعب." },
{ id:"ai-hoot", n:"AI is a Hoot", p:"CodeMonkey", u:"https://app.codemonkey.com/courses/ai-mini-course#1", img:"6sELDcy628NOH35GcicAFE/013c34f9d4685619a40280f22c817850/thumbnail_430_240.png", e:"🦉", g:[4,8], i:["ai","code"], t:"create", time:"hour", need:"webcam", hoai:true,
  en:"Train an AI on your poses, then code an owl that reacts to them.",
  ar:"درّب ذكاءً اصطناعياً على وضعيات جسمك ثم برمج بومة تتفاعل معها." },
{ id:"hackstack-social", n:"AI HackStack: Social Media Showdown", p:"CodeCombat", u:"https://codecombat.com/ai/play/hour-of-ai?utm_source=hour-of-ai", img:"6n7RjfBUqViRvalPqvNuhZ/f896190073d681315ce4d4306ab9f5b4/AI_HackStack_Social_Media_Showdown___430_x_240_.png", e:"📈", g:[6,12], i:["math","ai","safe"], t:"game", time:"hour", hoai:true,
  en:"Use algebra and AI prompts to model post engagement like a media manager.",
  ar:"استخدم الجبر وأوامر الذكاء الاصطناعي لتحليل تفاعل المنشورات كمدير تواصل اجتماعي." },
{ id:"hackstack-poetry", n:"AI HackStack: Poetry in Motion", p:"CodeCombat", u:"https://codecombat.com/ai/play/hour-of-ai?utm_source=hour-of-ai", img:"16CrkMltRlqYvfIYhErWWg/aeffea134799ba20d1843c8a24c99114/AI_HackStack_Poetry_in_Motion__480_x_360_.png", e:"📝", g:[6,12], i:["lang","art","ai"], t:"create", time:"hour", hoai:true,
  en:"Illustrate a poem with AI images, then critique the results for bias.",
  ar:"صوّر قصيدة بصور الذكاء الاصطناعي ثم انتقد النتائج بحثاً عن التحيّز." },
{ id:"codecombat-esports", n:"CodeCombat: AI Esports", p:"CodeCombat", u:"https://codecombat.com/ai/play/hour-of-ai?utm_source=hour-of-ai", img:"7xo63SAUUeGpU4UQxFoGlM/77123c1fc614c4f8aba7049f0f073b87/CodeCombat_AI_League__480_x_360_.png", e:"🏆", g:[6,12], i:["code","ai"], t:"game", time:"long", hoai:true,
  en:"Learn algorithms and prompting, then battle in the arena with an AI teammate.",
  ar:"تعلّم الخوارزميات وكتابة الأوامر ثم نافس في الساحة مع زميل ذكي." },
{ id:"activeai", n:"ActiveAI Literacy Modules", p:"ActiveAI × Junyi Academy", u:"https://app.active-ai.io/hour_of_ai", img:"3ogu7C010oD4SbrRxhMxeK/608d42d8ceda1a61178532d08093f185/cover_junyi_activeai.png", e:"🤖", g:[6,12], i:["ai"], t:"course", time:"long", hoai:true,
  en:"Bite-size interactive lessons: explore, build and judge AI systems.",
  ar:"دروس تفاعلية قصيرة: استكشف أنظمة الذكاء الاصطناعي وابنِها وقيّمها." },
{ id:"imagi-python", n:"Creative Coding with Python & AI", p:"imagi", u:"https://imagilabs.com/pages/hour-of-code-creative-python", img:"794gqVMBEOyzZ2uetQLfnl/1ba627c834f7f4cfd45e70f12d60fa87/cover-creative-python-small.png", e:"🎨", g:[6,12], i:["code","art"], t:"create", time:"hour", hoai:true,
  en:"Learn Python basics by coding pixel art, with an AI debugging buddy.",
  ar:"تعلّم أساسيات بايثون برسم فن البكسل، مع مساعد ذكي لتصحيح الأخطاء." },
{ id:"vibe-coding", n:"Vibe Coding: Your First Game", p:"Lovable × imagi", u:"https://imagilabs.com/pages/hour-of-code-vibe-coding", img:"6XSOKpDVSQoQrzGKZSCRD3/c57c32079568d3d752957c32b5e3da1d/cover-vibe-coding-small.png", e:"✨", g:[9,12], i:["code","ai"], t:"create", time:"hour", hoai:true,
  en:"Learn what prompts are, then build and customise your own game with AI.",
  ar:"تعرّف على الأوامر النصية ثم ابنِ لعبتك الخاصة وخصّصها بالذكاء الاصطناعي." },
{ id:"pacman", n:"Code Your Pac-Man Game", p:"FHNW Switzerland", u:"https://ruler.game/?tutorial=Pac-Man_Hour-of-AI-US", img:"3a7N32u1IOch73dbaLokNI/8d2d3c17df7ca1a7e5eb937a4688d2a3/Cover_Hour_of_AI_PacMan.jpg", e:"🟡", g:[4,8], i:["code","ai"], t:"game", time:"hour", hoai:true,
  en:"Build your own Pac-Man level and program the ghosts' simple AI rules.",
  ar:"ابنِ مستوى باك-مان الخاص بك وبرمج قواعد الذكاء البسيطة للأشباح." },
{ id:"megaminds", n:"MegaMinds: AI Ethics", p:"MegaMinds", u:"https://dash.megaminds.world/explore/130/ai-literacy-ethics", img:"5zPzTouqW3aoAfo42dHYlB/7537567573b5062ace4ad49a2b6db5be/megamindsAILiteracyBundle.jpg", e:"⚖️", g:[6,12], i:["safe","ai"], t:"game", time:"hour", hoai:true,
  en:"Talk to AI characters, uncover bias and write your own AI ethics statement.",
  ar:"حاور شخصيات ذكية، واكشف التحيّز، واكتب بيان أخلاقيات الذكاء الاصطناعي الخاص بك." },
{ id:"adobe-dream", n:"Create Your Dream Product", p:"Adobe Express", u:"https://new.express.adobe.com/design/template/urn:aaid:sc:VA6C2:14f97752-2381-5881-bbe9-5ad5f4c18737?learn=exercise%3Aexpress%2Fhow-to%2Fin-app%2Flearn-generative-ai%3A-1&category=search&cgen=GMCWXZM3&mv=other", img:"4g58hJUO8dpmviw2BhhBI1/fd68a658271042ef261ce0304fdf0edb/adobe_createyourdreamproduct.jpg", e:"💡", g:[8,12], i:["art","career","ai"], t:"create", time:"hour", need:"account", hoai:true,
  en:"Invent a product, design its logo or ad and visualise it with generative AI.",
  ar:"ابتكر منتجاً، وصمّم شعاره أو إعلانه، وتخيّله بالذكاء الاصطناعي التوليدي." },
{ id:"pictoblox-face", n:"Face Filters in PictoBlox", p:"STEMpedia", u:"https://ai.thestempedia.com/project/make-your-own-face-filters-in-pictoblox-using-the-face-detection/", img:"7DmPYoCGQ4mmiSHrRwH3fD/8fe7a98b5e9721e67a420164f4579498/20260710_Face_filters.png", e:"🕶️", g:[4,7], i:["ai","art","code"], t:"create", time:"hour", need:"webcam", hoai:true,
  en:"Use face-landmark AI to put fun graphics on faces in real time.",
  ar:"استخدم ذكاء تحديد ملامح الوجه لإضافة رسومات مرحة على الوجوه مباشرة." },
{ id:"pictoblox-bird", n:"Flying Bird Body-Control Game", p:"STEMpedia", u:"https://ai.thestempedia.com/project/flying-bird-game-using-human-body-detection-extension-pictoblox/", img:"1kEg3yPvJ1H0CQHZZ5m51c/3e024079a019113ca7468f4f32f37926/20260710_Flappy_Bird_game.png", e:"🐦", g:[4,8], i:["ai","code"], t:"create", time:"hour", need:"webcam", hoai:true,
  en:"Make a flying-bird game you control with your whole body — no keyboard.",
  ar:"اصنع لعبة طائر تتحكّم بها بجسمك كله — بدون لوحة مفاتيح." },
{ id:"pictoblox-banana", n:"AI Plant-Disease Detector", p:"STEMpedia", u:"https://ai.thestempedia.com/project/detect-banana-leaf-diseases-using-ai-in-pictoblox/", img:"2leQGXa5BXw7Jnz17xSxcY/5e4ea124f1cfab2bd7ea11a5c77c7329/20260710_banana_leaf_disease_detect.jpg", e:"🍃", g:[8,12], i:["ai","sci"], t:"create", time:"hour", hoai:true,
  en:"Train an image classifier to spot diseased leaves — AI for smart farming.",
  ar:"درّب مصنّف صور لاكتشاف الأوراق المريضة — الذكاء الاصطناعي للزراعة الذكية." },
{ id:"coco-js", n:"JavaScript + AI: Classifying Art", p:"Coco Coders", u:"https://www.cococoders.com/hour-of-ai-javascript", img:"3b6wEoBRLDdHtgKG0yyJU/16825175d26ad9daadb39bb1a49bb9bd/HourofAI_Project_JavaScript1.png", e:"🖼️", g:[5,9], i:["code","ai","art"], t:"create", time:"hour", hoai:true,
  en:"Discover how AI spots art forgeries, then code a drawing classifier.",
  ar:"اكتشف كيف يكشف الذكاء الاصطناعي اللوحات المزيّفة ثم برمج مصنّفاً للرسومات." },
{ id:"neuron", n:"How to Think Like a Neuron", p:"AI4GA", u:"https://ai4ga.org/think-like-a-neuron/", img:"0Z4sEuRITMeY9J4f0fs7F/96356bab148085f81b03485af7ce9a30/ThinkLikeANeuron.png", e:"⚡", g:[8,12], i:["ai","math"], t:"puzzle", time:"long", hoai:true,
  en:"Maths puzzles where you tune a neuron until it fires — how neural nets work.",
  ar:"ألغاز رياضية تضبط فيها خلية عصبية حتى تنشط — هكذا تعمل الشبكات العصبية." },
{ id:"feynman", n:"The Feynman Technique", p:"JoySchooler", u:"https://joyschooler.com/course/learning-science/lesson/feynman", img:"5pKPQstlftqg5Nus8QqOn4/49aa485cda7c3635fae931e973cdab86/feynman-cover.png", e:"🎓", g:[6,12], i:["lang","career"], t:"course", time:"hour", hoai:true,
  en:"Learn how to learn: explain ideas simply to find what you really understand.",
  ar:"تعلّم كيف تتعلّم: اشرح الأفكار ببساطة لتكتشف ما تفهمه حقاً." },

/* ---------------- More AI ---------------- */
{ id:"teachable", n:"Teachable Machine", p:"Google", u:"https://teachablemachine.withgoogle.com/", e:"📷", g:[4,12], i:["ai","sci"], t:"create", time:"quick", need:"webcam",
  en:"Train your own image, sound or pose model in minutes — no code needed.",
  ar:"درّب نموذجك الخاص للصور أو الأصوات أو الحركات خلال دقائق — بدون برمجة." },
{ id:"quickdraw", n:"Quick, Draw!", p:"Google", u:"https://quickdraw.withgoogle.com/", e:"✏️", g:[4,12], i:["ai","art"], t:"game", time:"quick",
  en:"Doodle fast — can a neural network guess what you're drawing?",
  ar:"ارسم بسرعة — هل تستطيع الشبكة العصبية أن تخمّن ما ترسمه؟" },
{ id:"ml4kids", n:"Machine Learning for Kids", p:"Dale Lane / IBM", u:"https://machinelearningforkids.co.uk/", e:"🧪", g:[5,10], i:["ai","code"], t:"create", time:"long",
  en:"Train AI models and use them in your own Scratch games.",
  ar:"درّب نماذج ذكاء اصطناعي واستخدمها في ألعاب سكراتش الخاصة بك." },
{ id:"which-face", n:"Which Face Is Real?", p:"University of Washington", u:"https://www.whichfaceisreal.com/", e:"🎭", g:[8,12], i:["ai","safe"], t:"puzzle", time:"quick",
  en:"Two faces, one made by AI. Train your eye to spot deepfakes.",
  ar:"وجهان، أحدهما من صنع الذكاء الاصطناعي. درّب عينك على كشف التزييف." },
{ id:"elements-ai", n:"Elements of AI", p:"University of Helsinki", u:"https://www.elementsofai.com/", e:"🎓", g:[10,12], i:["ai","career"], t:"course", time:"long", cert:true, need:"account",
  en:"A free, world-famous AI course with a university certificate at the end.",
  ar:"دورة ذكاء اصطناعي مجانية وشهيرة عالمياً مع شهادة جامعية في النهاية." },
{ id:"cs50ai", n:"CS50 AI with Python", p:"Harvard University", u:"https://cs50.harvard.edu/ai/", e:"🏛️", g:[11,12], i:["ai","code"], t:"course", time:"long", cert:true, need:"account",
  en:"Harvard's intro to AI: search, games, neural networks — free certificate.",
  ar:"مقدمة هارفارد للذكاء الاصطناعي: البحث والألعاب والشبكات العصبية — بشهادة مجانية." },

/* ---------------- Coding ---------------- */
{ id:"scratch", n:"Scratch", p:"MIT", u:"https://scratch.mit.edu/projects/editor/?tutorial=getStarted", e:"🐱", g:[4,9], i:["code","art"], t:"create", time:"hour",
  en:"Drag-and-drop coding — make your own games, stories and animations.",
  ar:"برمجة بالسحب والإفلات — اصنع ألعابك وقصصك ورسومك المتحركة." },
{ id:"blockly", n:"Blockly Games", p:"Google", u:"https://blockly.games/", e:"🧩", g:[4,8], i:["code"], t:"puzzle", time:"hour",
  en:"Puzzle, maze, bird and turtle levels that grow you into a real programmer.",
  ar:"مستويات ألغاز ومتاهات وسلحفاة تحوّلك تدريجياً إلى مبرمج حقيقي." },
{ id:"codecombat", n:"CodeCombat", p:"CodeCombat", u:"https://codecombat.com/play", e:"⚔️", g:[5,12], i:["code"], t:"game", time:"long",
  en:"Type real Python or JavaScript to guide your hero through dungeons.",
  ar:"اكتب أوامر بايثون أو جافاسكربت حقيقية لتقود بطلك عبر المتاهات." },
{ id:"appinventor", n:"MIT App Inventor", p:"MIT", u:"https://appinventor.mit.edu/", e:"📱", g:[6,12], i:["code","build"], t:"create", time:"long", need:"account",
  en:"Build real Android apps with blocks and try them on your phone.",
  ar:"ابنِ تطبيقات أندرويد حقيقية بالكتل وجرّبها على هاتفك." },
{ id:"flexbox", n:"Flexbox Froggy", p:"Codepip", u:"https://flexboxfroggy.com/", e:"🐸", g:[7,12], i:["code"], t:"puzzle", time:"quick",
  en:"Help the frogs reach their lily pads by writing CSS — web design as a game.",
  ar:"ساعد الضفادع للوصول إلى أوراقها بكتابة CSS — تصميم الويب كلعبة." },
{ id:"gridgarden", n:"Grid Garden", p:"Codepip", u:"https://cssgridgarden.com/", e:"🥕", g:[7,12], i:["code"], t:"puzzle", time:"quick",
  en:"Water your carrot garden using CSS Grid — 28 short levels.",
  ar:"اسقِ حديقة الجزر باستخدام CSS Grid — 28 مستوى قصيراً." },
{ id:"sql-mystery", n:"SQL Murder Mystery", p:"Northwestern Knight Lab", u:"https://mystery.knightlab.com/", e:"🔎", g:[9,12], i:["code","math"], t:"puzzle", time:"hour",
  en:"A crime happened in SQL City — query the database to catch the culprit.",
  ar:"وقعت جريمة في مدينة SQL — استعلم قاعدة البيانات لتكشف الفاعل." },
{ id:"elevator", n:"Elevator Saga", p:"Magnus Wolffelt", u:"https://play.elevatorsaga.com/", e:"🛗", g:[10,12], i:["code","math"], t:"puzzle", time:"long",
  en:"Program elevators in JavaScript to move people as efficiently as possible.",
  ar:"برمج المصاعد بجافاسكربت لنقل الناس بأعلى كفاءة ممكنة." },
{ id:"codewars", n:"Codewars", p:"Codewars", u:"https://www.codewars.com/", e:"🥋", g:[9,12], i:["code"], t:"puzzle", time:"quick", need:"account",
  en:"Short coding 'kata' challenges in Python and more — rank up like a martial artist.",
  ar:"تحديات برمجية قصيرة بلغة بايثون وغيرها — ارتقِ في الرتب كلاعب فنون قتالية." },
{ id:"khan-computing", n:"Khan Academy Computing", p:"Khan Academy", u:"https://www.khanacademy.org/computing", e:"💻", g:[6,12], i:["code"], t:"course", time:"long",
  en:"Free programming, animation and computer science lessons.",
  ar:"دروس مجانية في البرمجة والرسوم المتحركة وعلوم الحاسوب." },
{ id:"fcc", n:"freeCodeCamp", p:"freeCodeCamp", u:"https://www.freecodecamp.org/learn", e:"🔥", g:[9,12], i:["code","career"], t:"course", time:"long", cert:true, need:"account",
  en:"Web development, Python and data courses — each ends in a free certification.",
  ar:"دورات تطوير ويب وبايثون وبيانات — تنتهي كل منها بشهادة مجانية." },
{ id:"cs50p", n:"CS50 Python", p:"Harvard University", u:"https://cs50.harvard.edu/python/", e:"🐍", g:[10,12], i:["code"], t:"course", time:"long", cert:true, need:"account",
  en:"Harvard's intro to programming with Python — free certificate at the end.",
  ar:"مقدمة هارفارد للبرمجة ببايثون — مع شهادة مجانية في النهاية." },
{ id:"cs50x", n:"CS50x Computer Science", p:"Harvard University", u:"https://cs50.harvard.edu/x/", e:"🏛️", g:[11,12], i:["code","career"], t:"course", time:"long", cert:true, need:"account",
  en:"The legendary intro to computer science — challenging and certified.",
  ar:"المقدمة الأسطورية لعلوم الحاسوب — تحدٍّ حقيقي مع شهادة." },
{ id:"kaggle", n:"Kaggle Learn", p:"Kaggle (Google)", u:"https://www.kaggle.com/learn", e:"📊", g:[10,12], i:["code","ai","math"], t:"course", time:"long", cert:true, need:"account",
  en:"Short hands-on courses: Python, Pandas, Machine Learning — free certificates.",
  ar:"دورات عملية قصيرة: بايثون وPandas وتعلّم الآلة — بشهادات مجانية." },
{ id:"netacad-python", n:"Python Essentials 1", p:"Cisco Networking Academy", u:"https://www.netacad.com/courses/python-essentials-1", e:"🐍", g:[11,12], i:["code","career"], t:"course", time:"long", cert:true, need:"account",
  en:"Industry-aligned Python course with a Cisco certificate and badge.",
  ar:"دورة بايثون مرتبطة بسوق العمل مع شهادة وشارة من سيسكو." },

/* ---------------- Maths & logic ---------------- */
{ id:"khan", n:"Khan Academy", p:"Khan Academy", u:"https://www.khanacademy.org/", e:"📘", g:[4,12], i:["math","sci"], t:"course", time:"long",
  en:"Free maths and science lessons with mastery points as you go.",
  ar:"دروس مجانية في الرياضيات والعلوم مع نقاط إتقان أثناء تقدّمك." },
{ id:"desmos", n:"Desmos Graphing", p:"Desmos", u:"https://www.desmos.com/calculator", e:"📐", g:[7,12], i:["math","art"], t:"create", time:"hour",
  en:"Explore functions — or draw a whole picture using only equations.",
  ar:"استكشف الدوال — أو ارسم صورة كاملة باستخدام المعادلات فقط." },
{ id:"polypad", n:"Polypad", p:"Amplify / Mathigon", u:"https://polypad.amplify.com/", e:"🔷", g:[4,9], i:["math"], t:"create", time:"hour",
  en:"A virtual maths playground — tiles, fractions, geometry and number bars.",
  ar:"ملعب رياضيات افتراضي — بلاطات وكسور وهندسة وأشرطة أعداد." },
{ id:"euclidea", n:"Euclidea", p:"Horis International", u:"https://www.euclidea.xyz/", e:"📏", g:[8,12], i:["math"], t:"puzzle", time:"quick",
  en:"Geometry construction puzzles with just a compass and a straightedge.",
  ar:"ألغاز إنشاءات هندسية باستخدام الفرجار والمسطرة فقط." },
{ id:"nerdle", n:"Nerdle", p:"Nerdle", u:"https://www.nerdlegame.com/", e:"➗", g:[6,12], i:["math"], t:"puzzle", time:"quick",
  en:"A daily maths equation puzzle — six guesses to find the hidden sum.",
  ar:"لغز معادلة رياضية يومي — ست محاولات لإيجاد المعادلة المخفية." },
{ id:"lichess", n:"Lichess: Learn Chess", p:"Lichess (non-profit)", u:"https://lichess.org/learn", e:"♟️", g:[4,12], i:["math"], t:"puzzle", time:"quick",
  en:"Free, ad-free chess lessons and puzzles that train strategic thinking.",
  ar:"دروس وألغاز شطرنج مجانية بلا إعلانات تدرّب التفكير الاستراتيجي." },
{ id:"prodigy", n:"Prodigy Math", p:"Prodigy", u:"https://www.prodigygame.com/", e:"🧙", g:[4,7], i:["math"], t:"game", time:"hour", need:"account",
  en:"A maths adventure game — practice disguised as play.",
  ar:"لعبة مغامرات رياضية — تدريب في هيئة لعب." },

/* ---------------- Science ---------------- */
{ id:"phet", n:"PhET Simulations", p:"University of Colorado", u:"https://phet.colorado.edu/", e:"⚛️", g:[4,12], i:["sci","math"], t:"create", time:"hour",
  en:"Hundreds of free physics, chemistry and maths simulations (Arabic too).",
  ar:"مئات المحاكاة المجانية في الفيزياء والكيمياء والرياضيات (متوفرة بالعربية)." },
{ id:"spaceplace", n:"NASA Space Place", p:"NASA", u:"https://spaceplace.nasa.gov/", e:"🪐", g:[4,7], i:["sci"], t:"game", time:"quick",
  en:"Space games, crafts and facts straight from NASA.",
  ar:"ألعاب وأنشطة ومعلومات عن الفضاء مباشرة من ناسا." },
{ id:"foldit", n:"Foldit", p:"University of Washington", u:"https://fold.it/", e:"🧬", g:[9,12], i:["sci"], t:"puzzle", time:"long", need:"download",
  en:"Fold proteins in a puzzle game — your solutions help real scientists.",
  ar:"اطوِ البروتينات في لعبة ألغاز — حلولك تساعد علماء حقيقيين." },
{ id:"eterna", n:"Eterna", p:"Stanford & CMU", u:"https://eternagame.org/", e:"🧫", g:[9,12], i:["sci"], t:"puzzle", time:"long", need:"account",
  en:"Design RNA molecules in puzzles that feed into real medical research.",
  ar:"صمّم جزيئات RNA في ألغاز تساهم في أبحاث طبية حقيقية." },
{ id:"zooniverse", n:"Zooniverse", p:"Zooniverse", u:"https://www.zooniverse.org/", e:"🔭", g:[6,12], i:["sci"], t:"puzzle", time:"quick",
  en:"Be a citizen scientist — classify galaxies, animals and more for real research.",
  ar:"كن عالماً مواطناً — صنّف المجرات والحيوانات وغيرها لأبحاث حقيقية." },
{ id:"madrasa", n:"Madrasa", p:"Mohammed bin Rashid Global Initiatives", u:"https://madrasa.org/", e:"🇦🇪", g:[4,12], i:["sci","math","lang"], t:"course", time:"hour",
  en:"Free Arabic video lessons in science and maths from a UAE initiative.",
  ar:"دروس فيديو مجانية بالعربية في العلوم والرياضيات من مبادرة إماراتية." },

/* ---------------- Art, design & music ---------------- */
{ id:"musiclab", n:"Chrome Music Lab", p:"Google", u:"https://musiclab.chromeexperiments.com/", e:"🎹", g:[4,8], i:["art","sci"], t:"create", time:"quick",
  en:"Play with rhythm, melody and sound waves in simple music experiments.",
  ar:"العب بالإيقاع واللحن والموجات الصوتية في تجارب موسيقية بسيطة." },
{ id:"autodraw", n:"AutoDraw", p:"Google", u:"https://www.autodraw.com/", e:"🖍️", g:[4,9], i:["art","ai"], t:"create", time:"quick",
  en:"Sketch something and AI suggests a clean drawing — design posters fast.",
  ar:"ارسم أي شيء ويقترح الذكاء الاصطناعي رسماً أنيقاً — صمّم ملصقات بسرعة." },
{ id:"canva-school", n:"Canva Design School", p:"Canva", u:"https://www.canva.com/designschool/", e:"🎨", g:[8,12], i:["art","career"], t:"course", time:"hour",
  en:"Short design courses — layout, colour, typography and branding.",
  ar:"دورات تصميم قصيرة — التخطيط والألوان والخطوط والهوية البصرية." },
{ id:"tinkercad", n:"Tinkercad 3D & Circuits", p:"Autodesk", u:"https://www.tinkercad.com/", e:"🧊", g:[6,12], i:["build","art","code"], t:"create", time:"long", need:"account",
  en:"Design 3D models and wire virtual Arduino circuits in your browser.",
  ar:"صمّم نماذج ثلاثية الأبعاد ووصّل دوائر أردوينو افتراضية في المتصفح." },

/* ---------------- Engineering, robotics & electronics ---------------- */
{ id:"wokwi", n:"Wokwi Arduino Simulator", p:"Wokwi", u:"https://wokwi.com/", e:"🔌", g:[9,12], i:["build","code"], t:"create", time:"hour",
  en:"Build and code Arduino and ESP32 projects in a free online simulator.",
  ar:"ابنِ وبرمج مشاريع أردوينو وESP32 في محاكٍ مجاني على الإنترنت." },
{ id:"mblock", n:"mBlock", p:"Makeblock", u:"https://ide.mblock.cc/", e:"🤖", g:[5,9], i:["build","code","ai"], t:"create", time:"hour",
  en:"Program mBot and sprites with blocks or Python — our robotics platform.",
  ar:"برمج روبوت mBot والشخصيات بالكتل أو بايثون — منصة الروبوتات في مدرستنا." },
{ id:"makecode-microbit", n:"MakeCode micro:bit", p:"Microsoft", u:"https://makecode.microbit.org/", e:"🟩", g:[4,9], i:["build","code"], t:"create", time:"hour",
  en:"Code a micro:bit in the on-screen simulator — no device needed.",
  ar:"برمج لوحة micro:bit في المحاكي على الشاشة — بدون الحاجة للجهاز." },

/* ---------------- Languages & reading ---------------- */
{ id:"duolingo", n:"Duolingo", p:"Duolingo", u:"https://www.duolingo.com/", e:"🦜", g:[4,12], i:["lang"], t:"game", time:"quick", need:"account",
  en:"Bite-size language lessons — English, French, Arabic and more.",
  ar:"دروس لغوية قصيرة — إنجليزي وفرنسي وعربي وغيرها." },
{ id:"freerice", n:"Freerice", p:"UN World Food Programme", u:"https://freerice.com/", e:"🍚", g:[4,12], i:["lang","math"], t:"game", time:"quick",
  en:"Answer vocabulary and maths questions — every right answer donates rice.",
  ar:"أجب عن أسئلة المفردات والرياضيات — كل إجابة صحيحة تتبرّع بالأرز." },
{ id:"typingclub", n:"TypingClub", p:"TypingClub", u:"https://www.typingclub.com/", e:"⌨️", g:[4,9], i:["lang","career"], t:"course", time:"quick", cert:true,
  en:"Learn touch typing step by step — a skill you'll use for years.",
  ar:"تعلّم الكتابة باللمس خطوة بخطوة — مهارة ستستخدمها لسنوات." },

/* ---------------- Digital safety & media literacy ---------------- */
{ id:"interland", n:"Interland", p:"Google Be Internet Awesome", u:"https://beinternetawesome.withgoogle.com/en_us/interland", e:"🏝️", g:[4,7], i:["safe"], t:"game", time:"quick",
  en:"Four islands of online-safety adventures: phishing, privacy and kindness.",
  ar:"أربع جزر من مغامرات الأمان الرقمي: التصيّد والخصوصية واللطف." },
{ id:"badnews", n:"Bad News", p:"University of Cambridge", u:"https://www.getbadnews.com/", e:"📰", g:[9,12], i:["safe","lang"], t:"game", time:"quick",
  en:"Play a fake-news tycoon to learn how misinformation tricks people.",
  ar:"العب دور صانع أخبار مزيّفة لتتعلّم كيف تخدع المعلومات المضلّلة الناس." },
{ id:"harmony", n:"Harmony Square", p:"University of Cambridge", u:"https://harmonysquare.game/", e:"🏘️", g:[9,12], i:["safe"], t:"game", time:"quick",
  en:"See how online manipulation divides a town — and learn to resist it.",
  ar:"شاهد كيف يفرّق التلاعب الإلكتروني سكان بلدة — وتعلّم مقاومته." },
{ id:"netacad-cyber", n:"Introduction to Cybersecurity", p:"Cisco Networking Academy", u:"https://www.netacad.com/courses/introduction-to-cybersecurity", e:"🛡️", g:[9,12], i:["safe","career"], t:"course", time:"long", cert:true, need:"account",
  en:"Learn how to protect yourself and organisations online — Cisco badge.",
  ar:"تعلّم كيف تحمي نفسك والمؤسسات على الإنترنت — مع شارة من سيسكو." },
{ id:"picoctf", n:"picoCTF", p:"Carnegie Mellon University", u:"https://picoctf.org/", e:"🚩", g:[9,12], i:["safe","code"], t:"puzzle", time:"long", need:"account",
  en:"Capture-the-flag hacking puzzles designed for high-school students.",
  ar:"ألغاز أمن سيبراني (التقاط العلم) مصمّمة لطلاب المرحلة الثانوية." },

/* ---------------- Future & careers ---------------- */
{ id:"skillsbuild", n:"IBM SkillsBuild", p:"IBM", u:"https://skillsbuild.org/", e:"🎖️", g:[9,12], i:["career","ai","safe"], t:"course", time:"long", cert:true, need:"account",
  en:"Free courses in AI, cybersecurity and workplace skills with digital badges.",
  ar:"دورات مجانية في الذكاء الاصطناعي والأمن السيبراني ومهارات العمل مع شارات رقمية." },
{ id:"mslearn", n:"Microsoft Learn: AI Skills", p:"Microsoft", u:"https://learn.microsoft.com/training/", e:"🪟", g:[10,12], i:["career","ai","code"], t:"course", time:"long", cert:true, need:"account",
  en:"Free learning paths with badges and trophies — AI, cloud and data.",
  ar:"مسارات تعلّم مجانية مع شارات وجوائز — الذكاء الاصطناعي والسحابة والبيانات." },
{ id:"edraak", n:"Edraak", p:"Queen Rania Foundation", u:"https://www.edraak.org/", e:"📗", g:[9,12], i:["career","lang"], t:"course", time:"long", cert:true, need:"account",
  en:"Arabic online courses — from programming to life skills — with certificates.",
  ar:"دورات عربية على الإنترنت — من البرمجة إلى المهارات الحياتية — مع شهادات." },
{ id:"coursera", n:"Coursera", p:"Coursera", u:"https://www.coursera.org/", e:"🎓", g:[11,12], i:["career"], t:"course", time:"long", cert:true, need:"account",
  en:"University courses — audit for free; some certificates need a fee.",
  ar:"دورات جامعية — الحضور مجاني؛ وبعض الشهادات برسوم." },
{ id:"edx", n:"edX", p:"edX", u:"https://www.edx.org/", e:"🏫", g:[11,12], i:["career"], t:"course", time:"long", cert:true, need:"account",
  en:"Courses from real universities — free to audit, certificates available.",
  ar:"دورات من جامعات حقيقية — الحضور مجاني مع إمكانية الحصول على شهادة." }
];

/* ---------- Grade 12 certificate pathways ---------- */
const PATHWAYS = [
  { id:"py",   e:"🐍", color:"#2F6FEB",
    title:{ en:"Python Programmer", ar:"مبرمج بايثون" },
    desc:{ en:"From your first line of code to a Harvard certificate.", ar:"من أول سطر برمجي إلى شهادة من هارفارد." },
    steps:["kaggle","cs50p","netacad-python"] },
  { id:"ai",   e:"🤖", color:"#8B3FE0",
    title:{ en:"AI Explorer", ar:"مستكشف الذكاء الاصطناعي" },
    desc:{ en:"Understand AI, then build it — perfect for university applications.", ar:"افهم الذكاء الاصطناعي ثم ابنِه — مثالي لطلبات الجامعة." },
    steps:["elements-ai","kaggle","cs50ai"] },
  { id:"cyber",e:"🛡️", color:"#0E9F6E",
    title:{ en:"Cyber Defender", ar:"مدافع سيبراني" },
    desc:{ en:"Protect systems and people — and prove it in real challenges.", ar:"احمِ الأنظمة والناس — وأثبت ذلك في تحديات حقيقية." },
    steps:["netacad-cyber","skillsbuild","picoctf"] },
  { id:"web",  e:"🌐", color:"#E0671B",
    title:{ en:"Web Developer", ar:"مطوّر ويب" },
    desc:{ en:"Design and ship real websites, one certification at a time.", ar:"صمّم وانشر مواقع حقيقية، شهادة تلو الأخرى." },
    steps:["flexbox","fcc","cs50x"] }
];
